package MDLPA;

import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle.Messages;

@ConvertAsProperties(
        dtd = "-//MDLPA//LabelPropagationSettingsPanel//EN",
        autostore = false
)
@ActionID(category = "Window", id = "MDLPA")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@Messages({
    "CTL_LabelPropagationSettingsPanelAction=MDLPASettingsPanel",
    "CTL_LabelPropagationSettingsPanelTopComponent=MDLPASettingsPanel Window",
    "HINT_LabelPropagationSettingsPanelTopComponent=This is a MDLPASettingsPanel window"
})
public class MDLPASettingsPanel extends javax.swing.JPanel {
    public MDLPASettingsPanel() {
        initComponents();
    }
    
    void readProperties(java.util.Properties p) {
        // TODO 20 Read/write settings
        String version = p.getProperty("version");
    }

    void writeProperties(java.util.Properties p) {
        // TODO 20 Read/write settings
        p.setProperty("version", "1.0");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chkDisplayNodeMemberships = new javax.swing.JCheckBox();
        chkDisplayClustersAndRelevantDimensions = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        txtDimensionsSeparator = new javax.swing.JTextField();

        chkDisplayNodeMemberships.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(chkDisplayNodeMemberships, org.openide.util.NbBundle.getMessage(MDLPASettingsPanel.class, "MDLPASettingsPanel.chkDisplayNodeMemberships.text")); // NOI18N

        chkDisplayClustersAndRelevantDimensions.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(chkDisplayClustersAndRelevantDimensions, org.openide.util.NbBundle.getMessage(MDLPASettingsPanel.class, "MDLPASettingsPanel.chkDisplayClustersAndRelevantDimensions.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(MDLPASettingsPanel.class, "MDLPASettingsPanel.jLabel1.text")); // NOI18N

        txtDimensionsSeparator.setText(org.openide.util.NbBundle.getMessage(MDLPASettingsPanel.class, "MDLPASettingsPanel.txtDimensionsSeparator.text")); // NOI18N
        txtDimensionsSeparator.setToolTipText(org.openide.util.NbBundle.getMessage(MDLPASettingsPanel.class, "MDLPASettingsPanel.txtDimensionsSeparator.toolTipText")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(chkDisplayNodeMemberships, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(138, 138, 138))
            .addComponent(chkDisplayClustersAndRelevantDimensions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(txtDimensionsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(chkDisplayNodeMemberships)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkDisplayClustersAndRelevantDimensions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDimensionsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {chkDisplayClustersAndRelevantDimensions, chkDisplayNodeMemberships, jLabel1, txtDimensionsSeparator});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox chkDisplayClustersAndRelevantDimensions;
    public javax.swing.JCheckBox chkDisplayNodeMemberships;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txtDimensionsSeparator;
    // End of variables declaration//GEN-END:variables
}
